#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=28

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
cd "$REPO_ROOT"

ENV_FILE="$REPO_ROOT/.deploy-wizard.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cp "$REPO_ROOT/.deploy-wizard.env.example" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

die() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_value() {
  [[ -n "${2:-}" ]] || die "$1 cannot be empty"
}

validate_inputs() {
  [[ "$SERVER_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || die "Server host must be an IP address or hostname"
  [[ "$SERVER_PORT" =~ ^[0-9]+$ ]] || die "SSH port must be numeric"
  (( SERVER_PORT >= 1 && SERVER_PORT <= 65535 )) || die "SSH port must be between 1 and 65535"
  [[ "$SERVER_ADMIN_USER" =~ ^[a-z_][a-z0-9_-]*$ ]] || die "Administrator username is invalid"
  [[ "$DOCS_DOMAIN" =~ ^[A-Za-z0-9.-]+$ ]] || die "Document domain must not include https:// or a path"
  [[ "$GITHUB_REPOSITORY" =~ ^git@github\.com:[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+\.git$ ]] || \
    die "GitHub repository must use the git@github.com:owner/repository.git format"
}

admin_ssh() {
  ssh -p "$SERVER_PORT" "$SERVER_ADMIN_USER@$SERVER_HOST" "$@"
}

banner "VitePress GitHub deployment setup"

stage "Revoke the exposed GitHub token" 2
warn "The GitHub token previously pasted into chat must be treated as compromised."
open_url "https://github.com/settings/tokens"
step "Delete or revoke the exposed token. Do not paste a replacement token into this wizard."
if ! confirm "Have you revoked the exposed GitHub token?"; then
  die "Revoke the token before continuing"
fi

stage "Confirm deployment values" 3
say "Only non-secret setup values are saved to .deploy-wizard.env."
ask SERVER_HOST "Server IP or hostname:"
ask SERVER_PORT "SSH port:"
ask SERVER_ADMIN_USER "Current Debian administrator username:"
ask DOCS_DOMAIN "Documentation domain without https://:"
ask GITHUB_REPOSITORY "GitHub repository SSH URL:"
require_value "Server host" "$SERVER_HOST"
require_value "SSH port" "$SERVER_PORT"
require_value "Administrator username" "$SERVER_ADMIN_USER"
require_value "Document domain" "$DOCS_DOMAIN"
require_value "GitHub repository" "$GITHUB_REPOSITORY"
validate_inputs
write_env SERVER_HOST "$SERVER_HOST"
write_env SERVER_PORT "$SERVER_PORT"
write_env SERVER_ADMIN_USER "$SERVER_ADMIN_USER"
write_env DOCS_DOMAIN "$DOCS_DOMAIN"
write_env GITHUB_REPOSITORY "$GITHUB_REPOSITORY"

stage "Authenticate GitHub and configure origin" 3
if ! command -v gh >/dev/null 2>&1; then
  open_url "https://cli.github.com/"
  die "Install GitHub CLI, then run this wizard again"
fi
if ! gh auth status >/dev/null 2>&1; then
  step "GitHub will open a browser. Sign in and authorize GitHub CLI."
  gh auth login --hostname github.com --git-protocol ssh --web
fi
gh auth setup-git

CURRENT_ORIGIN=$(git remote get-url origin 2>/dev/null || true)
if [[ -z "$CURRENT_ORIGIN" ]]; then
  confirm "Add $GITHUB_REPOSITORY as git remote origin?" || die "Git remote was not configured"
  git remote add origin "$GITHUB_REPOSITORY"
elif [[ "$CURRENT_ORIGIN" != "$GITHUB_REPOSITORY" ]]; then
  warn "Current origin is $CURRENT_ORIGIN"
  confirm "Replace it with $GITHUB_REPOSITORY?" || die "Git remote does not match"
  git remote set-url origin "$GITHUB_REPOSITORY"
fi
gh repo view >/dev/null
GITHUB_WEB_URL=$(gh repo view --json url --jq '.url')
say "GitHub repository: $GITHUB_WEB_URL"

stage "Create the Cloudflare DNS record" 3
open_url "https://dash.cloudflare.com/"
step "Select ccttt99.com, then open DNS -> Records -> Add record."
step "Create or update the A record: name docs, IPv4 $SERVER_HOST, TTL Auto."
step "Set Proxy status to Proxied (orange cloud)."
confirm "Has the proxied DNS record been created?" || die "A proxied DNS record is required"

if command -v dig >/dev/null 2>&1; then
  RESOLVED_IP=$(dig +short A "$DOCS_DOMAIN" @1.1.1.1 | tail -n 1)
else
  RESOLVED_IP=$(getent ahostsv4 "$DOCS_DOMAIN" 2>/dev/null | awk 'NR == 1 { print $1 }')
fi
if [[ -n "$RESOLVED_IP" ]]; then
  say "DNS resolves through Cloudflare to $RESOLVED_IP."
  note "A proxied record returns a Cloudflare edge address, not the origin IP."
else
  warn "DNS does not resolve yet. Cloudflare changes can take time to propagate."
  pause "Press Enter to continue after the DNS record resolves."
fi

stage "Initialize the Debian 12 server" 4
say "This installs Nginx and rsync, creates deploy, and prepares /var/www/vitepress-docs."
PRECHECK_HOST_KEY=$(ssh-keyscan -p "$SERVER_PORT" -H -t ed25519 "$SERVER_HOST" 2>/dev/null)
[[ -n "$PRECHECK_HOST_KEY" ]] || die "Could not read the server SSH host key"
PRECHECK_FINGERPRINT=$(printf '%s\n' "$PRECHECK_HOST_KEY" | ssh-keygen -lf -)
say "Scanned SSH fingerprint: $PRECHECK_FINGERPRINT"
step "Open the hosting provider's web console and run: ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub"
confirm "Does the console SHA256 fingerprint match the scanned fingerprint?" || die "SSH host fingerprint did not match"
step "Before continuing, ensure the provider firewall allows SSH port $SERVER_PORT and origin HTTP on TCP 80."
confirm "Are the required firewall ports open?" || die "Open the firewall ports before continuing"
confirm "Run the Debian initialization commands on $SERVER_HOST?" || die "Server initialization was cancelled"
ssh -p "$SERVER_PORT" -t "$SERVER_ADMIN_USER@$SERVER_HOST" 'bash -s' <<'SERVER_SETUP'
set -euo pipefail
if [[ $(id -u) -eq 0 ]]; then
  SUDO=()
else
  SUDO=(sudo)
fi
"${SUDO[@]}" apt-get update
"${SUDO[@]}" apt-get install -y nginx rsync
if ! id deploy >/dev/null 2>&1; then
  "${SUDO[@]}" useradd --create-home --shell /bin/bash deploy
fi
"${SUDO[@]}" install -d -m 755 -o deploy -g deploy /var/www/vitepress-docs
"${SUDO[@]}" install -d -m 755 -o deploy -g deploy /var/www/vitepress-docs/releases
"${SUDO[@]}" systemctl enable --now nginx
SERVER_SETUP

stage "Create the deploy key and GitHub Secrets" 4
DEPLOY_KEY_PATH="$HOME/.ssh/vitepress_deploy"
if [[ ! -f "$DEPLOY_KEY_PATH" ]]; then
  install -m 700 -d "$HOME/.ssh"
  ssh-keygen -t ed25519 -N '' -C 'github-actions-vitepress' -f "$DEPLOY_KEY_PATH"
else
  note "Keeping existing deploy key: $DEPLOY_KEY_PATH"
fi

DEPLOY_PUBLIC_KEY=$(<"$DEPLOY_KEY_PATH.pub")
# Variables in this script expand on the remote host.
# shellcheck disable=SC2016
printf 'restrict %s\n' "$DEPLOY_PUBLIC_KEY" |
  admin_ssh 'set -euo pipefail
    TMP_KEY=$(mktemp)
    cat > "$TMP_KEY"
    if [[ $(id -u) -eq 0 ]]; then SUDO=(); else SUDO=(sudo); fi
    "${SUDO[@]}" install -d -m 700 -o deploy -g deploy /home/deploy/.ssh
    "${SUDO[@]}" install -m 600 -o deploy -g deploy "$TMP_KEY" /home/deploy/.ssh/authorized_keys
    rm -f "$TMP_KEY"'

SSH_KNOWN_HOSTS=$(ssh-keyscan -p "$SERVER_PORT" -H -t ed25519 "$SERVER_HOST" 2>/dev/null)
[[ -n "$SSH_KNOWN_HOSTS" ]] || die "Could not read the server SSH host key"
SCANNED_FINGERPRINT=$(printf '%s\n' "$SSH_KNOWN_HOSTS" | ssh-keygen -lf -)
SERVER_FINGERPRINT=$(admin_ssh 'ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub')
say "Server fingerprint:  $SERVER_FINGERPRINT"
say "Scanned fingerprint: $SCANNED_FINGERPRINT"
confirm "Do these SHA256 fingerprints match?" || die "SSH host fingerprint did not match"

ssh -p "$SERVER_PORT" -i "$DEPLOY_KEY_PATH" -o IdentitiesOnly=yes \
  deploy@"$SERVER_HOST" 'test -w /var/www/vitepress-docs && echo "deploy access: OK"'

SSH_PRIVATE_KEY=$(<"$DEPLOY_KEY_PATH")
set_secret SERVER_HOST "$SERVER_HOST"
set_secret SERVER_PORT "$SERVER_PORT"
set_secret SERVER_USER "deploy"
set_secret SSH_PRIVATE_KEY "$SSH_PRIVATE_KEY"
set_secret SSH_KNOWN_HOSTS "$SSH_KNOWN_HOSTS"
(( ${#SKIPPED[@]} == 0 )) || die "One or more GitHub Secrets were not set; fix GitHub CLI authentication and rerun"

stage "Install the Nginx site" 2
NGINX_CONFIG=$(mktemp)
trap 'rm -f "$NGINX_CONFIG"' EXIT
sed "s/docs\.example\.com/$DOCS_DOMAIN/g" "$REPO_ROOT/deploy/nginx.conf" > "$NGINX_CONFIG"
scp -P "$SERVER_PORT" "$NGINX_CONFIG" "$SERVER_ADMIN_USER@$SERVER_HOST:/tmp/vitepress-docs.nginx.conf"
# Variables in this script expand on the remote host.
# shellcheck disable=SC2016
admin_ssh 'set -euo pipefail
  if [[ $(id -u) -eq 0 ]]; then SUDO=(); else SUDO=(sudo); fi
  "${SUDO[@]}" install -m 644 /tmp/vitepress-docs.nginx.conf /etc/nginx/sites-available/vitepress-docs
  "${SUDO[@]}" ln -sfn /etc/nginx/sites-available/vitepress-docs /etc/nginx/sites-enabled/vitepress-docs
  "${SUDO[@]}" nginx -t
  "${SUDO[@]}" systemctl reload nginx
  rm -f /tmp/vitepress-docs.nginx.conf'
say "Nginx is ready. A 404 is expected until the first GitHub deployment finishes."

stage "Deploy and configure Cloudflare HTTPS" 7
if [[ -n "$(git status --short)" ]]; then
  warn "The working tree has uncommitted files. Only existing commits will be pushed."
  git status --short
fi
confirm "Push main to GitHub and trigger the first deployment?" || die "Initial push was cancelled"
git push -u origin main
open_url "$GITHUB_WEB_URL/actions"

RUN_ID=""
for _ in 1 2 3 4 5 6 7 8 9 10; do
  RUN_ID=$(gh run list --workflow deploy.yml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)
  [[ -n "$RUN_ID" ]] && break
  sleep 2
done
if [[ -n "$RUN_ID" ]]; then
  gh run watch "$RUN_ID" --exit-status
else
  warn "Could not find the workflow run automatically. Check the Actions page."
  pause "Press Enter after the deployment succeeds."
fi

if curl -fsSI --max-time 15 -H "Host: $DOCS_DOMAIN" "http://$SERVER_HOST/" >/dev/null; then
  say "The Nginx origin is reachable over HTTP."
else
  warn "Origin HTTP verification failed. Check TCP 80, Nginx, and the Actions log."
  pause "Press Enter after the origin works over HTTP."
fi

open_url "https://dash.cloudflare.com/"
step "Select ccttt99.com, open Rules -> Overview -> Create rule -> Configuration Rule."
step "Create docs-origin-http: match Hostname equals $DOCS_DOMAIN, set SSL to Flexible, then deploy it."
step "Open SSL/TLS -> Edge Certificates and enable Always Use HTTPS for the zone."
warn "Do not set the entire ccttt99.com zone to Flexible; the hostname rule keeps other origins unchanged."
warn "Do not add an HTTP-to-HTTPS redirect in Nginx; Flexible mode can otherwise cause a redirect loop."
confirm "Is the docs-only Flexible rule deployed with Always Use HTTPS enabled?" || die "Cloudflare HTTPS setup is required"

curl -fsSI --max-time 20 "https://$DOCS_DOMAIN/" >/dev/null || die "Public HTTPS verification failed"
say "Public HTTPS is working through Cloudflare."
open_url "https://$DOCS_DOMAIN/"
pause "Press Enter after checking the live documentation site."

finish
